#!/bin/bash

current_date=$(date +%Y-%m-%d)
highest_diff=0
highest_log=""
highest_host=""

for dir in /apps/continuity/nft/*/; do
    for logfile_head in "$dir"/engine*/log/Start_head*.log; do
        for logfile_tail in "$dir"/engine*/log/Start_tail*.log; do
            if [ -e "$logfile_tail" ] && [ "$(basename "$logfile_head")" == "$(basename "$logfile_tail" | sed 's/Start_tail/Start_head/')" ]; then
                head_date=$(head -n 1 "$logfile_head" | awk '{print $2,$3}')
                tail_date=$(tail -n 1 "$logfile_tail" | awk '{print $2,$3}')

                if [ -n "$head_date" ] && [ -n "$tail_date" ]; then
                    head_date_formatted=$(date -d "$head_date" +%Y-%m-%d)

                    if [ "$head_date_formatted" == "$current_date" ]; then
                        head_timestamp=$(date -d "$head_date" +%s)
                        tail_timestamp=$(date -d "$tail_date" +%s)
                        time_diff=$((tail_timestamp - head_timestamp))

                        if [ $time_diff -gt $highest_diff ]; then
                            highest_diff=$time_diff
                            highest_log=$(basename "$logfile_head")
                            highest_host=$(basename "$dir")
                        fi
                    fi
                fi
            fi
        done
    done
done

if [ $highest_diff -gt 0 ]; then
    echo "The highest time difference is $highest_diff seconds for log $highest_log on host $highest_host."
else
    echo "No logs found for today."
fi
